### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Taram1980** [bureaucratic-labs/dostoevsky#113]
Здравствуйте. 
Пробовал pip install dostoevsky, в ответ при установке получил кучу красного текста. Концовку скопировал:
ERROR: Command errored out with exit status 1: 'C:\Users\afecn\anaconda3.1\envs\ml\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\afecn\\AppData\\Local\\Temp\\pip-install-onr9g1p0\\fasttext\\setup.py'"'"'; __file__='"'"'C:\\Users\\afecn\\AppData\\Local\\Temp\\pip-install-onr9g1p0\\fasttext\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\afecn\AppData\Local\Temp\pip-record-t7yp1hx1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\afecn\anaconda3.1\envs\ml\Include\fasttext' Check the logs for full command output.

КТо нибудь сталкивался с подобной проблемой? Спасибо

**Comment by VladimirAugust** [comment]
Try to do advises from:
https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

**Comment by VladimirAugust** [comment]
The problem was with installing fasttext. This advise https://stackoverflow.com/questions/51683015/unable-to-install-fasttext-for-python-on-windows helped me
