### ISSUE TITLE
the model doesn't return a WordVectorModel or SupervisedModel anymore?

### ISSUE THREAD

**Issue by michaelschlitzer** [bureaucratic-labs/dostoevsky#143]
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

I'm trying to use this in Colab and it appears that everything loads correctly, but when I work through the given example with the three simple phrases, it fails, saying that:

ValueError: /usr/local/lib/python3.7/dist-packages/dostoevsky/data/models/fasttext-social-network-model.bin cannot be opened for loading!

I'm not sure what that means or how to proceed or what these error messages mean.  Do you have any advice?

**Comment by dveselov** [comment]
Hi,
It seems like model data wasn't loaded correctly, try to remove model (e.g. run `rm /usr/local/lib/python3.7/dist-packages/dostoevsky/data/models/fasttext-social-network-model.bin`) and then again execute `python -m dostoevsky download fasttext-social-network-model`
