### ISSUE TITLE
Some sentiment is "skip" - what is that?

### ISSUE THREAD

**Issue by GraphGrailAi** [bureaucratic-labs/dostoevsky#37]
All works but sometimes 
`print(message, '->', sentiment)`

produce "skip" result, not negative or positive, is there a way how to fix?

**Comment by dveselov** [comment]
Hi, you can read about it in RuSentiment README: https://github.com/text-machine-lab/rusentiment
> "skip" class for unclear cases, noisy posts, content that was likely not created by the users themselves (poems, lyrics, jokes etc.)
