### ISSUE TITLE
_lzma issue when trying to download models

### ISSUE THREAD

**Issue by tonko22** [bureaucratic-labs/dostoevsky#55]
Got 
```
  File "/usr/local/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```
when using` dostoevsky download fasttext-social-network-model` 
or `dostoevsky download vk-embeddings cnn-social-network-model` on Ubuntu 16.04, Python 3.6

Found info:

> It looks like Ubuntu does not include a Python 3 version of python-lzma. It might be more practical to use a different compression method for now.

Installing lzma via `pip install pylzma` and `sudo apt-get install liblzma-dev` did not help

**Comment by dveselov** [comment]
Hi,
Sorry, but I can't reproduce this bug. Can you provide a little bit more details about it?
I've tried to install `dostoevsky` inside docker container running on Ubuntu 16.04 and python 3.6 [(this dockerfile)](https://gist.github.com/monkut/c4c07059444fd06f3f8661e13ccac619):
```bash
$ docker build -t ubuntu1604py36 .
$ docker run --rm -ti ubuntu1604py36 bash -c "pip3 install dostoevsky && dostoevsky download fasttext-social-network-model"
```
And everything seems to be fine.

**Comment by tonko22** [comment]
Tested on another machine and everything worked, seems like i've broken something on current machine
