### ISSUE TITLE
[Question] Did it test on arm?

### ISSUE THREAD

**Issue by Ngoroth** [bureaucratic-labs/dostoevsky#70]
I'm triyng to use this library on RaspberryPi 4 and have some troubles.

Traceback (most recent call last):
  File "SentimentAnalyzer.py", line 3, in <module>
    from dostoevsky.models import FastTextSocialNetworkModel
ModuleNotFoundError: No module named 'dostoevsky'

But on win10 PC it works just fine.

Python version 3.7.3
No matter with virtual env on not
fasttext-social-network-model is downloaded
Trying with code snippet from readme
Running with sudo

Without sudo i getting another error

`ImportError: /home/pi/.local/lib/python3.7/site-packages/fasttext_pybind.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8 ...
`

**Comment by Ngoroth** [comment]
After several days i made it. I ran my project in docker on raspberry pi 4.

**Comment by dveselov** [comment]
Hi, I think ARM isn't supported by official `fasttext` bindings.
