### ISSUE TITLE
RuSentiment dataset?

### ISSUE THREAD

**Issue by grwlf** [bureaucratic-labs/dostoevsky#75]
Hi, may ask about RuSentiment dataset? It looks like it's original page [1] is dead, so could you please consider re-publishing it?

BR

[1] - http://text-machine.cs.uml.edu/lab2/data/suspended.html

**Comment by dveselov** [comment]
Hi, take it [here](https://storage.b-labs.pro/corpora/rusentiment.tar.xz).

**Comment by grwlf** [comment]
Thank you!

**Comment by grwlf** [comment]
For reference: Here is the results of multilingual Bert fine-tuning on this dataset. https://github.com/stagedml/stagedml/blob/master/run/rusentiment/out/Report.md
