### ISSUE TITLE
fasttext-social-network-model.bin cannot be opened for loading!

### ISSUE THREAD

**Issue by sal-ram** [bureaucratic-labs/dostoevsky#81]
I tried to run the tutorial code, but there was a mistake:

Traceback (most recent call last):
  File "train.py", line 8, in <module>
    model = FastTextSocialNetworkModel(tokenizer=tokenizer)
  File "C:\Users\Рамазан\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dostoevsky\models.py", line 61, in __init__
    super(FastTextSocialNetworkModel, self).__init__(
  File "C:\Users\Рамазан\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dostoevsky\models.py", line 26, in __init__
    self.get_compiled_model()
  File "C:\Users\Рамазан\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dostoevsky\models.py", line 69, in get_compiled_model
    return load_fasttext_model(self.MODEL_PATH)
  File "C:\Users\Рамазан\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fasttext\FastText.py", line 350, in load_model
    return _FastText(model_path=path)
  File "C:\Users\Рамазан\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fasttext\FastText.py", line 43, in __init__
    self.f.loadModel(model_path)
ValueError: C:\Users\Рамазан\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dostoevsky\data\models/fasttext-social-network-model.bin cannot be opened for loading!

Before that i had written this: $ python -m dostoevsky download fasttext-social-network-model

**Comment by VeritasVZ** [comment]
same with me

**Comment by gigantina** [comment]
Are you find a solution?

**Comment by dveselov** [comment]
Hi, try to download model weights manually and put it to `data\models` directory.  
Weights can be obtained [here](https://storage.b-labs.pro/models/fasttext-social-network-model.bin).  
Possibly, there is error in download process and we should implement some checksum-based checking feature in data downloader script.

**Comment by gigantina** [comment]
I have found a solution. Get Cyrillic characters out of the way

**Comment by ycj0217** [comment]
> Hi, try to download model weights manually and put it to `data\models` directory.
> Weights can be obtained [here](https://storage.b-labs.pro/models/fasttext-social-network-model.bin).
> Possibly, there is error in download process and we should implement some checksum-based checking feature in data downloader script.

Works

**Comment by EgShes** [comment]
As @dveselov said, you can [download](https://storage.b-labs.pro/models/fasttext-social-network-model.bin) weights manually. Then you can set path to your model before loading it
```
FastTextSocialNetworkModel.MODEL_PATH = '/<some_folders>/fasttext-social-network-model.bin'
model = FastTextSocialNetworkModel(tokenizer=tokenizer)
```

**Comment by Anturui** [comment]
FastTextSocialNetworkModel.MODEL_PATH = '/<some_folders>/fasttext-social-network-model.bin'
model = FastTextSocialNetworkModel(tokenizer=tokenizer)

It dose not work
Please HELP!
