### ISSUE TITLE
fasttext-social-network-model license?

### ISSUE THREAD

**Issue by RaviMa-Kore** [bureaucratic-labs/dostoevsky#84]
From the README of this repo, I can find that, **fasttext-social-network-model** was trained with [rusentiment](https://github.com/text-machine-lab/rusentiment) data. And the LICENSE of [rusentiment](https://github.com/text-machine-lab/rusentiment) dataset is Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

Can you please share the license type of **fasttext-social-network-model**? Is it MIT based as the code is?

**Comment by dveselov** [comment]
Hi, I think you can use fasttext weights under MIT license.  
Anyway, original dataset no longer available due VK.com request.  
Maybe @annargrs can give more info for us?
