### ISSUE TITLE
How to fix the error

### ISSUE THREAD

**Issue by mitabunov** [bureaucratic-labs/dostoevsky#85]
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-22-ad7133893fcf> in <module>()
      1 tokenizer = RegexTokenizer()
----> 2 model = FastTextSocialNetworkModel(tokenizer=tokenizer)
      3 sentiment_list = []
      4 results = model.predict(list_of_posts, k=3)
      5 for sentiment in results:

4 frames

/usr/local/lib/python3.6/dist-packages/fasttext/FastText.py in __init__(self, model_path, args)
     41         self.f = fasttext.fasttext()
     42         if model_path is not None:
---> 43             self.f.loadModel(model_path)
     44         self._words = None
     45         self._labels = None

ValueError: /usr/local/lib/python3.6/dist-packages/dostoevsky/data/models/fasttext-social-network-model.bin cannot be opened for loading!

Installing collected packages: dostoevsky
Successfully installed dostoevsky-0.5.0

**Comment by dveselov** [comment]
https://github.com/bureaucratic-labs/dostoevsky/issues/85
